/**
 * Seed values, transcribed from arbor-general job-scheduling SKILL.md v1.10 and
 * SCHEDULING_PLAYBOOK.md on 2026-09-19. These are the STARTING records; the office
 * supersedes them by chatting. Do not edit this file to change a live rule —
 * that is what set_config is for. Edit it only to correct the transcription.
 */
import type { Family, FamilyValue } from "./schema";

export const SEED_SET_BY = "seed:job-scheduling@1.10";

export const seed: { [F in Family]: FamilyValue<F> } = {
  roster: {
    people: [
      { name: "Ethan", climb: true, complex_rigging: "yes", crane_operator: true, lift: true, leader: true, cdl: true, active: true },
      { name: "Adam", climb: true, complex_rigging: "yes", crane_operator: true, lift: true, leader: true, cdl: true, active: true },
      { name: "Alex", climb: true, complex_rigging: "yes", crane_operator: false, lift: true, leader: true, cdl: true, active: true },
      { name: "Bob", climb: true, complex_rigging: "no", crane_operator: false, lift: true, leader: true, cdl: true, active: true },
      { name: "Nathan", climb: true, complex_rigging: "trainee", crane_operator: false, lift: true, leader: false, cdl: true, active: true, note: "Nate. Rigging trainee — does not satisfy the requirement alone." },
      { name: "Luke", climb: true, complex_rigging: "no", crane_operator: false, lift: true, leader: false, cdl: true, active: true },
      { name: "Ian", climb: true, complex_rigging: "no", crane_operator: false, lift: true, leader: false, cdl: true, active: true },
      { name: "James", climb: true, complex_rigging: "no", crane_operator: false, lift: false, leader: false, cdl: false, active: true, note: "Cannot run a lift." },
      { name: "Aaron", climb: false, complex_rigging: "no", crane_operator: false, lift: false, leader: false, cdl: false, active: true },
      { name: "Elijah", climb: false, complex_rigging: "no", crane_operator: false, lift: false, leader: false, cdl: false, active: true, note: "Grounds only. Justin wants him on a crew 1–2 days a week; check time off first." },
      { name: "Gavin", climb: false, complex_rigging: "no", crane_operator: false, lift: false, leader: false, cdl: false, active: true, started: "2026-08-03", note: "Full-time grounds." },
    ],
  },

  crew_rules: {
    hard: {
      never_pair: [["Ethan", "Bob"]],
      leaders: ["Ethan", "Adam", "Bob", "Alex"],
      max_crews: 4,
      min_cdl_standard_crew: 2,
      min_cdl_crane_crew: 3,
      crane_crew_size: 3,
      crane_operators: ["Ethan", "Adam"],
      complex_rigging_qualified: ["Ethan", "Alex", "Adam"],
      complex_rigging_tags: ["Heavy Rigging", "Climbing and Rigging", "Possible Rigging"],
      climbing_tags: ["Possible Climbing", "Climbing"],
      cannot_run_lift: ["James"],
    },
    soft: [
      { rule: "Get Elijah on a crew 1–2 days a week.", why: "Grounds-only; Justin wants him working. He is out some full weeks — check time off first." },
      { rule: "Keep Bob, James and Luke together where natural.", why: "The one genuinely stable crew (72 days together Apr–Jul 2026)." },
    ],
  },

  equipment: {
    pools: [
      { pool: "Lift", count: 4, tags: ["Any Lift", "Dino", "Nifty", "92' Spider Lift"], single_point: false, note: "92' Spider Lift = a Dino." },
      { pool: "Forwarder", count: 4, tags: ["Any Forwarding Machine", "Giant", "BM", "Mini Skid Steer"], single_point: false, note: "BM = Branch Manager = Giant." },
      { pool: "Grapple truck", count: 3, tags: ["Palfinger M13", "Grapple Picks", "Back Grapple In Driveway"], single_point: false },
      { pool: "Mini GRCS", count: 3, tags: ["Mini GRCS"], single_point: false },
      { pool: "Crane (Treezilla)", count: 1, tags: ["Treezilla", "50 Ton Knuckle Crane", "Crane", "Grapple Crane Picks"], single_point: true, rental: { item: "45 Ton National", from: "Erlinger Crane Co." }, note: "A second crane day is possible only with Erlinger booked — flag as an action, never assume." },
      { pool: "Cat loader", count: 1, tags: ["Cat", "Giant or cat"], single_point: true },
      { pool: "Serco", count: 1, tags: ["Serco"], single_point: true, note: "A specific knuckleboom on one of the 3 grapple trucks." },
      { pool: "Giant 2700", count: 1, tags: ["Giant 2700"], single_point: true, note: "One of the 4 Giants." },
    ],
    tag_notes: [
      { tag: "Dino / Any Forwarding Machine", meaning: "Requests BOTH a lift and a forwarder." },
      { tag: "Optional Treezilla", meaning: "A preference, not a requirement." },
    ],
  },

  dollar_targets: {
    mode: "quota_8h",
    targets: {
      two_man: { low: 4700, high: 4700 },
      three_man: { low: 5900, high: 6600 },
      four_man: { low: 7700, high: 7700 },
    },
    note: "Justin 2026-08-20: build to the crew-day dollar FLOOR on the 8:00–4:00 block; at or over the band the day is built. The ten-hour fill (playbook §3A) is documented and NOT active.",
  },

  day_shape: {
    block_start: "08:00",
    block_end: "16:00",
    production_days: ["Mon", "Tue", "Wed", "Thu"],
    buffer_minutes: { min: 60, max: 90 },
    arrival_window_minutes: { first_job: 60, later_job: 120, phc_stop: 120, emergency: null },
  },

  sizing: {
    crew_hour_rate: 275,
    three_man_elapsed_rate: 825,
    round_up_minutes: 30,
    table: [
      { max_price_exclusive: 1000, block_hours: 1.5, full_day: false },
      { max_price_exclusive: 2000, block_hours: 2.0, full_day: false },
      { max_price_exclusive: 3500, block_hours: 3.5, full_day: false },
      { max_price_exclusive: 6000, block_hours: 5.0, full_day: false },
      { max_price_exclusive: null, block_hours: null, full_day: true },
    ],
    adjustments: {
      two_man_multiplier: 1.5,
      four_man_multiplier: 0.75,
      crane_hours: 6,
      crane_full_day_lock: true,
      land_clearing_min_hours: 5,
      land_clearing_full_day_lock_over: 5000,
      phc_stop_minutes: 45,
      emergency_hours: 5,
      emergency_clears_crew_day: true,
    },
    over_price_ask: 6000,
    duration_hint_tags: ["1 Hour Job", "1-2 Hours", "2 Day Job", "May take 1-2 days", "2 Grapple Loads", "3-4 Grapple Loads"],
    size_on_tree_only_price: true,
  },

  dryness: {
    weather_point: { latitude: 38.8114, longitude: -89.9532 },
    past_days: 14,
    forecast_days: 7,
    severe_event_inches: 1.0,
    tiers: [
      { state: "wet", dry_days_min: 0, dry_days_max: 1, unlocks_tags: ["Wet weather work", "Possible wet weather"] },
      { state: "kind of dry", dry_days_min: 2, dry_days_max: 4, unlocks_tags: ["Needs To Be Kinda Dry", "Dryish"] },
      { state: "dry", dry_days_min: 5, dry_days_max: 8, unlocks_tags: ["Needs To Be Dry"] },
      { state: "very dry", dry_days_min: 8, dry_days_max: null, unlocks_tags: ["Needs To Be Very Dry"] },
    ],
    severe_requires_human: true,
  },

  hard_blocks: {
    on_hold_marker: "ON HOLD",
    date_restricted_patterns: ["Fall Work", "(Oct/Nov)", "(After April 20)", "(Mid September)"],
    named_day_pattern: "<Weekday> job",
    notice_pattern: "3-4 DAY NOTICE",
    utility_line_drop_tags: ["Power Line Drop", "Street Light Line Drop"],
    utility_lead_time_weeks: { min: 1, max: 2 },
    not_a_blocker_tags: ["Communication Line Drop"],
    irrelevant_tags: ["Shane Needed", "adam lead", "Trade Out", "No Commission", "* Estimate", "Pipeline Automation", "<insurance carrier names>"],
  },

  tiers: {
    preempt: ["Insurance", "Storm damage"],
    priority_tags: ["Priority Job", "Priority"],
    sunday_parked_is_ready_queue: true,
    pools: [
      { pool: "Tree", capacity: "the tree crews (2–4)", competes_with_crews: true },
      { pool: "Crane", capacity: "Crew A + Treezilla only", competes_with_crews: true },
      { pool: "Stump", capacity: "Shane / Eric, subcontracted", competes_with_crews: false },
      { pool: "PHC", capacity: "Jeff, solo", competes_with_crews: false },
    ],
    lead_time_formula: "backlog $ in pool ÷ trailing weekly completed $ in pool, per pool, never blended",
    lead_time_by_revenue_not_count: true,
    age_clock_starts_when_schedulable: true,
  },

  placeholders: {
    map: [
      { assignee: "Nic", crew: "Crew A" },
      { assignee: "Justin", crew: "Crew B" },
      { assignee: "Elizabeth", crew: "Crew C" },
    ],
    real_names_mean_firm: true,
  },

  yard: {
    address: "4757 New Poag Road, Edwardsville IL 62025",
    latitude: 38.8008436,
    longitude: -90.0402244,
    road_factor: 1.25,
    loaded_mph: 35,
    density_zips: ["62025", "62034", "62269", "62062", "62234", "62040", "62294", "62002"],
  },

  storm_protocol: {
    designated_crew_history: ["Adam", "Ethan", "Nathan", "Ian"],
    block_hours: 5,
    displaced_work_moves_to: "Fri",
    call_displaced_customers_same_day: true,
  },

  overtime: {
    workweek: "Sun-Sat",
    threshold_hours: 40,
    premium_per_hour: 34.64,
    never_decline_emergency: true,
    revenue_per_man_hour: { tree: 246, crane: 394, emergency: 434 },
  },

  site_notes: { notes: [] },

  known_one_day: { jobs: [] },

  write_policy: {
    notify_pro_on_schedule: false,
    note: "The customer text (notify) is never a setting — write_schedule hard-codes it off and only notify_customer sends it. notify_pro is the crew text; off while boards are tentative (the office UI has no such switch, the API does).",
  },
};
